### ISSUE TITLE
forward is misspelled

### ISSUE THREAD

**Issue by robinwhittleton** [kingrpaul/herminie-templeton-kavanagh_darby-ogill-and-the-good-people#1]
In the scans this is a “Foreword”, so the file name, section id and title all need fixing.

**Comment by kingrpaul** [comment]
211555a6b5c86b31db3a9dcc262104bead0bb3cd

**Comment by robinwhittleton** [comment]
It should be Forew**o**rd (with an “o”). See https://www.daisy.org/z3998/2012/vocab/structure/#document-sections. Can you fix?

**Comment by kingrpaul** [comment]
> It should be Forew**o**rd (with an “o”). See https://www.daisy.org/z3998/2012/vocab/structure/#document-sections. Can you fix?

58302fad2585532868041acae63400055e0ebaf6
