### ISSUE TITLE
Verses should be separated with paragraphs

### ISSUE THREAD

**Issue by robinwhittleton** [kingrpaul/herminie-templeton-kavanagh_darby-ogill-and-the-good-people#2]
There are a couple of places ([preface](https://github.com/kingrpaul/herminie-templeton-kavanagh_darby-ogill-and-the-good-people/blob/314781d812a3359cacbc9714dd2d58bb259e6656/src/epub/text/preface.xhtml#L28-L29), [King Brian](https://github.com/kingrpaul/herminie-templeton-kavanagh_darby-ogill-and-the-good-people/blob/main/src/epub/text/the-adventures-of-king-brian-connors.xhtml#L87-L88)) that try to separate verses with two breaks. You should close the paragraph and open a new one instead. There’s an example at the end of https://standardebooks.org/manual/1.6.3/single-page#7.5.

You’ll also need to include the `p + p` styling from https://standardebooks.org/manual/1.6.3/single-page#7.5.1.

**Comment by kingrpaul** [comment]
5f067d039a31e891b2267c02e5ba548a24b05bd8
8a79ea3e481ac1bea932a6a542fa82e8fe0f8b8f
