### ISSUE TITLE
A few runs of capital letters need fixing

### ISSUE THREAD

**Issue by robinwhittleton** [kingrpaul/herminie-templeton-kavanagh_darby-ogill-and-the-good-people#3]
- First word of darby-ogill-and-the-leprechaun
- First word of chapter 3 of the-adventures-of-king-brian-connors
- In the-banshees-comb `at-TIN-tion` should be `at-<strong>tin</strong>-tion` (that’ll automatically style it to use small caps, which is what we want)

**Comment by kingrpaul** [comment]
d44f56817303f7db8e3287d37dc45b9a0ce404f0

**Comment by kingrpaul** [comment]
d44f56817303f7db8e3287d37dc45b9a0ce404f0
