### ISSUE TITLE
Some drawn-out words should have non-breaking hyphens

### ISSUE THREAD

**Issue by robinwhittleton** [kingrpaul/herminie-templeton-kavanagh_darby-ogill-and-the-good-people#4]
When a word is stretched out for prosaic effect we should use non-breaking hyphens (see https://standardebooks.org/manual/1.6.3/single-page#8.7.7.6).

I’ve collected a few examples, but there might be more:
- “gr-r-reat” in the-convarsion-of-father-cassidy
- “Who-o-o? who-o-o?” in darby-ogill-and-the-good-people
- “car-r-ress” in the-adventures-of-king-brian-connors

**Comment by kingrpaul** [comment]
1a111574ac28335ed706bd8c6f31c932210c401a
