### ISSUE TITLE
Remove “Chap.” from subheadings

### ISSUE THREAD

**Issue by robinwhittleton** [kingrpaul/herminie-templeton-kavanagh_darby-ogill-and-the-good-people#5]
We remove references to chapters in headings. So, for example:
```
<h3>
	<span epub:type="label">Chap.</span>
	<span epub:type="ordinal z3998:roman">I</span>
</h3>
```
should be:
```
<h3 epub:type="ordinal z3998:roman">I</h3>
```
This is an issue in the-banshees-comb and the-adventures-of-king-brian-connors.

**Comment by kingrpaul** [comment]
2ae8130be4b5b52c0818f018120e6ea95982d6dc

**Comment by robinwhittleton** [comment]
Thanks! You’ll need to regenerate the ToC as well.

**Comment by kingrpaul** [comment]
> Thanks! You’ll need to regenerate the ToC as well.

df9774b63a668b1c275582a9a83e3379042153d5
