### ISSUE TITLE
Various small issues in the-banshees-comb

### ISSUE THREAD

**Issue by robinwhittleton** [kingrpaul/herminie-templeton-kavanagh_darby-ogill-and-the-good-people#6]
- At 22k words this would be a `se:novella`, not a `se:short-story`
- Subchapters can have `epub:type="z3998:subchapter"` instead of `epub:type="chapter"`
- We’d also typically use numbers instead of roman numbers in the ids
- Remove roman semantics from `The top <span epub:type="z3998:roman">iv</span> the day`

**Comment by kingrpaul** [comment]
79f8f9d16ea0da0b5e331c1a8be7ea593e6a06cd

**Comment by kingrpaul** [comment]
The de-linter warns about "subchapter", and this was "ignore"d.

**Comment by robinwhittleton** [comment]
Lint is complaining because it should be `z3998:subchapter`, not `subchapter`. Can you fix, and remove the lint ignore rule?

**Comment by kingrpaul** [comment]
> Lint is complaining because it should be `z3998:subchapter`, not `subchapter`. Can you fix, and remove the lint ignore rule?

d6147d298d41b2701b89e823aad292f3f218bcd7
