### ISSUE TITLE
We should use Irish English, not British English

### ISSUE THREAD

**Issue by robinwhittleton** [kingrpaul/herminie-templeton-kavanagh_darby-ogill-and-the-good-people#9]
Could you find and replace `en-GB` with `en-IE`?

**Comment by kingrpaul** [comment]
1dc390e26dfbe69e2b92a099b4d18a1f253fc30f

**Comment by kingrpaul** [comment]
Reverted to en-GB as en-IE breaks se build.
f9a1260747bdc0f868407a6987f656904b971c1f
This books appears to have been written and published in the US, but I found an instances of the "colour" and "favour."

**Comment by robinwhittleton** [comment]
I’m going to amend the build tooling to support `en-IE`, and we can change that back when that’s done.

**Comment by kingrpaul** [comment]
> I’m going to amend the build tooling to support `en-IE`, and we can change that back when that’s done.

Not clear if the amend will be before or after release and have set the language to 'en-IE'. Just let me know if that's not correct for the present.
